#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : croniter
Version  : 0.3.17
Release  : 31
URL      : http://pypi.debian.net/croniter/croniter-0.3.17.tar.gz
Source0  : http://pypi.debian.net/croniter/croniter-0.3.17.tar.gz
Summary  : croniter provides iteration for datetime object with cron like format
Group    : Development/Tools
License  : MIT
Requires: croniter-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
Introduction
============
.. contents::
croniter provides iteration for the datetime object with a cron like format.

%package python
Summary: python components for the croniter package.
Group: Default

%description python
python components for the croniter package.


%prep
%setup -q -n croniter-0.3.17

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1495476817
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1495476817
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
